name: "Build APK"
runs-on: ubuntu-latest

permissions:
  contents: write
  pull-requests: write

timeout-minutes: 30

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Validate Gradle Wrapper
    uses: gradle/wrapper-validation-action@v3

  - name: Set up JDK 17
    uses: actions/setup-java@v4
    with:
      distribution: 'zulu'
      java-version: 17

  - name: Make gradlew executable
    run: chmod +x ./gradlew

  - name: Check build-logic
    run: ./gradlew check -p build-logic

  - name: Build debug APK
    run: ./gradlew app:assembleDebug