name: "Coverage Report"
runs-on: ubuntu-latest

needs:
  - unit_tests
  - android_tests

if: always()

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Set up JDK 17
    uses: actions/setup-java@v4
    with:
      distribution: 'zulu'
      java-version: 17

  # Adjust paths and commands as per your project's Jacoco configuration
  - name: Generate JaCoCo coverage report
    run: ./gradlew createDemoDebugJacocoReport

  - name: Display local test coverage
    id: jacoco
    uses: madrapps/jacoco-report@v1.6.1
    with:
      title: Combined test coverage report
      min-coverage-overall: 40
      min-coverage-changed-files: 60
      paths: |
        ${{ github.workspace }}/**/build/reports/jacoco/**/*Report.xml
      token: ${{ secrets.GITHUB_TOKEN }}

  - name: Upload coverage reports
    uses: actions/upload-artifact@v4
    with:
      name: coverage-reports
      if-no-files-found: error
      compression-level: 1
      overwrite: false
      path: '**/build/reports/jacoco/'

  - name: Upload test reports
    uses: actions/upload-artifact@v4
    with:
      name: test-reports
      path: '**/build/reports/androidTests'